title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
#github:
#  repository_url: repoexample.com/download
#  zip_url: http://example.com/download.zip
#  tar_url: another value
