title: Jasmine Moore
description: Professional Portfolio
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  repository_url: http://jasmine-shanay.github.io/portfolio/
  cv_url: http://jasmine-shanay.github.io/portfolio//webpages/cv
  writing_url: http://jasmine-shanay.github.io/portfolio/webpages//writing
  data_url: http://jasmine-shanay.github.io/portfolio/webpages//data
  contact_url: https://jasmine-shanay.github.io/portfolio/webpages//contact
#  another_url: https://jasmine-shanay.github.io/portfolio/webpages//another-page
