title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  repository_url: http://jasmine-shanay.github.io/Cayman-theme/
  writing_url: https://jasmine-shanay.github.io/jasminemoore/writing/
  zip_url: http://example.com/download.zip
  tar_url: https://jasmine-shanay.github.io/Cayman-theme/another-page.html
  contact_url: https://jasmine-shanay.github.io/Cayman-theme/contact
