title: Jasmine Moore
description: Professional Portfolio
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  repository_url: http://jasmine-shanay.github.io/Cayman-theme/
  cv_url: http://jasmine-shanay.github.io/Cayman-theme/cv
  writing_url: http://jasmine-shanay.github.io/Cayman-theme/writing
  data_url: http://jasmine-shanay.github.io/Cayman-theme/data
  contact_url: https://jasmine-shanay.github.io/Cayman-theme/contact
  another_url: https://jasmine-shanay.github.io/Cayman-theme/another-page
